### PR TITLE
add info for EOS project

### PR DESCRIPTION
**Pull request by cyntss**

### CODE REVIEW

**Comment by cyntss** [comment]
@Ana06 Hi Ana. I'm adding the EOS project to the mentoring list as we would like our project to participate in GSoC next year.
Please let me know if there is anything else you would need.. I'll create issues in the upcoming days.
Thank you!

**Comment by cyntss** [comment]
@Ana06 for some reason I can't see EOS at https://101.opensuse.org/. Could you kindly check what happened?

**Comment by Ana06** [comment]
@cyntss 

> @Ana06 for some reason I can't see EOS at https://101.opensuse.org/. Could you kindly check what happened?

I am not sure, it may be that the issue was tagged after the page was built and it will appear with the new PR. the page need anyway to be prepared for the next GSoC, so do not worry.

@cyntss I also wonder something else. How does this project relate with openSUSE? Sorry for my ignorance, but it seems to me like it is only to be used at SUSE and if that is the case and I think it can not be part of GSoC as according to Google rules, the project have to capture the needs of your openSUSE.

**Comment by cyntss** [comment]
@Ana06 EOS is an open source Design System. At the moment when you enter the design system you can see SUSE's guidelines, but the design system itself is open source, and our contribution or intention is to help other open source projects create their design systems to improve consistency.

At the same time, we deliver eos-icons, which is also an open source library and is used in a few (we are still new) open source projects. This is all new, we released EOS in August, so we still don't have much traction in the open source community, but we have to start somewhere.

**Comment by cyntss** [comment]
Also @Ana06, I realize that you may be looking at our current landing page, which is all about SUSE atm. That is about to change in the next days. I just wanted to mention it as we are working on a release for next week that is changing that initial all-about-SUSE direction we had in our first release, and we are becoming more open

**Comment by foursixnine** [comment]
@cyntss I stand by @Ana06's point: Is this used by openSUSE at all or is there any plan to use that within openSUSE before GSoC?. I can understand that new projects have to start somewhere, but it's openSUSE that's in the GSoC and not SUSE.

**Comment by Ana06** [comment]
@cyntss according to Google rules, it does not only need to be open source, but also to capture the needs of openSUSE. So, I think that if there are plans to be used in openSUSE it is fine, but if not it would out of scope. In other words, the projects needs to help openSUSE in some way. :disappointed:

**Comment by cyntss** [comment]
Absolutely, I understand. And I'm 100% sure that EOS is of great value to openSUSE. Just the landing page of openSUSE alone will benefit from EOS and all the elements, icons, and components we are creating with it, not to even mention all the subdomains like software.opensuse.org,  build.opensuse.org, etc. 
There are big plans for openSUSE, we want to help all openSUSE products be aligned and provide cohesive experiences to their users. These are all discussions that are just starting. I'm gonna talk to @ddemaio about this in the next days. Just rest assured that EOS's goal is to help the openSUSE and open source community, that has been made clear at a manager's level within SUSE too. It is the direction we are heading into and it is embraced by SUSE.

**Comment by lagartoflojo** [comment]
> Just the landing page of openSUSE alone will benefit from EOS and all the elements, icons, and components we are creating with it, not to even mention all the subdomains like software.opensuse.org, build.opensuse.org, etc.

Could the GSoC project then be about re-building an existing openSUSE website using EOS, instead of the proposed "Web UI Builder"?

**Comment by lagartoflojo** [comment]
> Just the landing page of openSUSE alone will benefit from EOS and all the elements, icons, and components we are creating with it, not to even mention all the subdomains like software.opensuse.org, build.opensuse.org, etc.

Could the GSoC project then be about re-building an existing openSUSE website using EOS, instead of the proposed "Web UI Builder"?

**Comment by Ana06** [comment]
@lagartoflojo 

> Could the GSoC project then be about re-building an existing openSUSE website using EOS, instead of the proposed "Web UI Builder"?

This would need a bit more discussion with the people already involved in that project I guess. But something like that could fix better :wink:

**Comment by cyntss** [comment]
Hi @Ana06 @ddemaio, can we please revisit this? I know we won't [sadly] be in GSoC this year, but it would still be nice if we could have EOS in the projects page as it isn't only valuable for GSoC but also to other students looking into open source projects to dive into.

Just in case you haven't seen it, we made the openSUSE Design System using EOS as foundation http://opensuse.eosdesignsystem.com .. and we will continue improving it as we work on new features for EOS.

**Comment by Ana06** [comment]
@cyntss this page was originally created for GSoC (as it is required by Google). I think it won't be maintained from now on... Someone would have to take of it.

**Comment by cyntss** [comment]
@Ana06 I can certainly do that. How should we do it?

**Pull request merged**
