### PR TITLE
Add new project for mentoring, the bml

### PR DESCRIPTION
**Pull request by nicolasbock**

### CODE REVIEW

**Comment by ChrisBr** [comment]
Hmm, how is this related to openSUSE?

**Comment by nicolasbock** [comment]
Maybe I am misunderstanding the goal of 101.opensuse.org, but looking at the other advertised projects, I didn't see much relation there either. How are Portus and Jangouts related to OpenSUSE? As far as I can tell they are regular open source projects.

**Comment by ChrisBr** [comment]
Hmm, Portus is a SUSE project and Jangouts is used by many openSUSE/SUSE (and the core contributers are from openSUSE). Can you elaborate how openSUSE would benefit from bml?

**Comment by nicolasbock** [comment]
Like I said, maybe I am misunderstanding the goal of 101. I took it to be a channel to help connect people looking to get involved with open source work with people that are willing to mentor. I didn't interpreted the fact that this is done under the OpenSUSE umbrella to mean that the projects are purely OpenSUSE related. So to answer your question: The benefit I see is that an increased number of projects under 101 improve the visibility of 101 and by association OpenSUSE.

**Comment by nicolasbock** [comment]
...

**Comment by ChrisBr** [comment]
@nicolasbock sry, I was on vacation and then forgot about this one! GSoC for this year is anyway running at the moment. But I'm open to include BML in the next iteration :)

Sorry again for the delay

**Comment by nicolasbock** [comment]
Thanks!

**Comment by ChrisBr** [comment]
@nicolasbock is still valid for GSoC?

**Pull request closed without merging**
