### PR TITLE
Revamp based on openSUSE Jekyll theme

### PR DESCRIPTION
**Pull request by hellcp**
| Before | After |
|---|---|
|openSUSE 101|openSUSE 101|
|openSUSE GSoC |openSUSE GSoC|

### CODE REVIEW

**Comment by hellcp** [comment]
Summary of technical changes:
* Added a possibility to store more than one year of GSoC projects
* Made it easier to setup new pages without the need to mess with css
* Excluded a bunch of files which aren't needed on the server
* Replaced a whole bunch of pages to be markdown (might change a few more)
* Replaced fontawesome with remix icons

**Comment by hennevogel** [comment]
96 files changed, one commit. This is not reviewable :smile_cat:

**Comment by hellcp** [comment]
Yeah, I will split it into something more manageable in a sec

**Comment by hellcp** [comment]
@hennevogel my seconds last 3 weeks apparently, but this should be good to review now

**Pull request merged**
