### PR TITLE
A few fixes in style and link

### PR DESCRIPTION
**Pull request by sonalkr132**
It changes

screenshot from 2016-02-12 10-19-24

to:
screenshot from 2016-02-12 09-57-52

**EDIT:**
Dropped changed of `background-size`

### CODE REVIEW

**Comment by ChrisBr** [comment]
bfb17ca is good to go but I don't like the GSoC background image in dd49274 because it breaks with the front page ...
@hennevogel what do you think?

**Comment by hennevogel** [comment]
Yeah please drop the background-size change

**Comment by sonalkr132** [comment]
I have updated my PR.

**Comment by hennevogel** [comment]
Thanks @sonalkr132 :-)

**Pull request merged**
