### PR TITLE
Fix the display of GSoC issues

### PR DESCRIPTION
**Pull request by hellcp**

### CODE REVIEW

**Comment by ddemaio** [comment]
HI @hellcp Do you happen to know if the fix here broke something on 101.o.o? I no longer see the issues displaying. Carrier and Phoebe should be displaying the "Let's do it", but it isn't showing.

**Comment by hellcp** [comment]
`Uncaught Error: Syntax error, unrecognized expression: .Carrier - PaaS [Platform as a service]-table .list-group`
spaces in the project names aren't gonna work

I'm not sure why phoebe doesn't work though

**Comment by ddemaio** [comment]
Thx @hellcp  I made some changes and removed the spaces, but some of the  "PaaS [Platform as a service]" still shows on 101.o.o after I changed the file. The issue (https://github.com/openSUSE/mentoring/issues/153) also isn't posting. It looks correct, but it isn't replicating to the webpage. I'm a bit lost on what is missing or what is causing the issue for it not to post. There is an theme error email I get. It says "You are attempting to use a Jekyll theme, "jekyll-theme-opensuse", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://docs.github.com/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll." Could that be it.

**Comment by hellcp** [comment]
Try hard refreshing, I can see it working on 101.o.o just fine

**Pull request merged**
